baseurl = "http://localhost:1313/"
title = "Heerise"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[services]
  [services.disqus]
  shortname = ""
  [services.googleAnalytics]
  id = ""

[pagination]
  pagerSize = 10

# ============================================================
# Main Menu
# ============================================================
[menu]
[[menu.main]]
  name       = "Home"
  identifier = "menu.home"
  url        = "/"
  weight     = 1

[[menu.main]]
  name       = "Blog"
  identifier = "menu.blog"
  url        = "/blog/"
  weight     = 2

[[menu.main]]
  name       = "FAQ"
  identifier = "menu.faq"
  url        = "/faq/"
  weight     = 3

[[menu.main]]
  identifier = "contact"
  name       = "Contact"
  url        = "/contact/"
  weight     = 4

# Top bar social links
[[menu.topbar]]
  weight = 1
  name   = "Phone"
  url    = "tel:+12 34 567 89 01"
  pre    = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
  weight = 2
  name   = "GitHub"
  url    = "https://github.com"
  pre    = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
  weight = 3
  name   = "Email"
  url    = "mailto:hello@heerise.com"
  pre    = "<i class='fas fa-2x fa-envelope'></i>"

# ============================================================
# Site Params
# ============================================================
[params]
  viewMorePostLink = "/blog/"
  author = "Heerise Team"
  defaultKeywords = ["heerise", "career", "coaching"]
  mainSections = ["blog"]
  defaultDescription = "Heerise - Your Career Coach Platform"

  # Social media
  facebook_site = ""
  twitter_site = ""
  default_sharing_image = "img/sharing-default.png"

  # Google Maps (disabled by default)
  enableGoogleMaps = false
  googleMapsApiKey = ""

  latitude = ""
  longitude = ""

  # Style: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
  style = "default"

  # Contact form (Formspree)
  formspree_action = ""
  contact_form_ajax = false
  enableRecaptchaInContactForm = false
  googleRecaptchaKey = ""

  about_us = "<p>Heerise is your AI-powered career coaching platform.</p>"
  copyright = "Copyright (c) 2025 - 2026, Heerise. All rights reserved."

  date_format = "January 2, 2006"

  dropdown_mouse_over = false

  disabled_logo = false
  logo_text = "Heerise"

  logo = "img/logo.png"
  logo_small = "img/logo-small.png"
  contact_url = "/contact"
  address = """<p class="text-uppercase"><strong>Heerise</strong>
    <br>Your Career Coach
    <br><strong>Online Platform</strong>
  </p>
  """

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

# Top bar
[params.topbar]
  enable = true
  text = """<p>Contact us at hello@heerise.com</p>"""

# Sidebar widgets
[params.widgets]
  categories = true
  tags = true
  search = true

# Carousel settings
[params.carouselCustomers]
  items = 6
  auto_play = false
  slide_speed = 2000
  pagination_speed = 1000

[params.carouselTestimonials]
  items = 4
  auto_play = false
  slide_speed = 2000
  pagination_speed = 1000

[params.carouselHomepage]
  enable = true
  auto_play = true
  slide_speed = 2000
  pagination_speed = 1000

# Features section
[params.features]
  enable = true
  cols = 3

# Testimonials section
[params.testimonials]
  enable = true
  title = "Testimonials"
  subtitle = "Hear from our users about their career transformation journey."

# See more section
[params.see_more]
  enable = true
  icon = "far fa-file-alt"
  title = "Do you want to see more?"
  subtitle = "Explore how Heerise can accelerate your career growth."
  link_url = "#"
  link_text = "Learn More"

# Clients section
[params.clients]
  enable = true
  title = "Our Partners"
  subtitle = ""

# Recent posts section
[params.recent_posts]
  enable = true
  title = "From our blog"
  subtitle = "Latest insights on career development and professional growth."
  hide_summary = false

[params.footer.recent_posts]
  enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
